/**
 * The site's signature illustration: a wheelchair-accessible maxi taxi.
 *
 * The artwork lives in `public/brand/taxi*.svg`, generated by
 * `scripts/build-taxi-svg.mjs` — edit it there, not here, then run
 * `npm run build:taxi`.
 *
 * WHY A FILE RATHER THAN INLINE SVG
 *
 * The taxi appears up to a dozen times on a page. Inlined it cost ~6 KB of
 * markup per copy, and React serialises the tree a second time into the RSC
 * payload, so closer to 12 KB each. That made the home page 310 KB of HTML and
 * the services page 448 KB — roughly half of it the same vehicle repeated.
 *
 * As a file the browser fetches one ~7 KB SVG, caches it, and every further
 * instance costs one `<img>` tag. The CSS animations declared inside the SVG
 * still run when it is loaded through `<img>`, and the `prefers-reduced-motion`
 * query inside it still honours the viewer's system setting — so the vehicle
 * behaves exactly as before.
 */

export type MaxiTaxiProps = {
  className?: string;
  /** Deploy the rear wheelchair ramp. */
  rampDown?: boolean;
  /** Draw motion streaks trailing behind. */
  streaks?: boolean;
  /**
   * Accessible name. Pass "" for instances that are purely decorative — the
   * image then has an empty alt and screen readers skip it.
   */
  title?: string;
  /**
   * Load eagerly at high priority. Use only for the one above the fold on a
   * page; everything else should stay lazy.
   */
  priority?: boolean;
};

function variantFor(rampDown: boolean, streaks: boolean) {
  if (rampDown && streaks) return "taxi-ramp-streaks";
  if (rampDown) return "taxi-ramp";
  if (streaks) return "taxi-streaks";
  return "taxi";
}

export function MaxiTaxi({
  className = "",
  rampDown = false,
  streaks = false,
  title = "Wheelchair accessible maxi taxi",
  priority = false,
}: MaxiTaxiProps) {
  return (
    // Deliberately a plain <img>, not next/image: the source is a vector, so
    // there is nothing for the optimiser to resize, and routing it through
    // /_next/image would only add a round trip.
    // eslint-disable-next-line @next/next/no-img-element
    <img
      src={`/brand/${variantFor(rampDown, streaks)}.svg`}
      alt={title}
      width={260}
      height={130}
      className={className}
      loading={priority ? "eager" : "lazy"}
      fetchPriority={priority ? "high" : "auto"}
      decoding="async"
      draggable={false}
    />
  );
}

/**
 * A strip of road with dashes sliding underneath — pair with <MaxiTaxi /> to
 * sell the illusion that a stationary vehicle is moving.
 *
 * The dashes are one painted gradient rather than the 30 `<span>`s this used to
 * render. Multiplied by the strips on a page, and again by React's serialised
 * payload, those nodes were a measurable share of every document.
 */
export function RoadStrip({
  className = "",
  tone = "light",
}: {
  className?: string;
  /** "light" = pale track for dark backgrounds; "dark" = grey track for light ones. */
  tone?: "light" | "dark" | "accent";
}) {
  const track = {
    light: "bg-white/10",
    dark: "bg-night-200",
    accent: "bg-white/10",
  }[tone];

  // `road-dashes` paints from currentColor, so the dash colour is just a text
  // colour on the moving layer.
  const dash = {
    light: "text-taxi-500/70",
    dark: "text-night-400",
    accent: "text-access-500/60",
  }[tone];

  return (
    <div
      className={`relative h-2 overflow-hidden rounded-full ${track} ${className}`}
      aria-hidden="true"
    >
      <div
        className={`animate-road road-dashes absolute inset-y-0 left-0 w-[calc(100%+120px)] ${dash}`}
      />
    </div>
  );
}
